# ./demand-forecastor/Dockerfile
FROM python:3.11-slim

ENV TZ=Europe/Rome \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# (psycopg2-binary evita dipendenze di sistema)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# code
COPY app.py /app/app.py

# directory to persist the model
RUN mkdir -p /app/model
VOLUME ["/app/model"]

# default: run once per day
# (you can pass SLEEP_SECS from compose, default 86400)
ENV SLEEP_SECS=86400

CMD python /app/app.py && sleep ${SLEEP_SECS}
