version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  simulator:
    build:
      context: ./simulator
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092


  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


#   mongo-express:
#     image: mongo-express
#     ports:
#       - "8081:8081"
#     depends_on:
#       - mongodb
#     environment:
#       - ME_CONFIG_MONGODB_SERVER=mongodb
#       - ME_CONFIG_BASICAUTH_USERNAME=admin
#       - ME_CONFIG_BASICAUTH_PASSWORD=admin

#   flink-jobmanager:
#     image: flink:1.17
#     ports:
#       - "8082:8081" # Flink web UI
#     command: jobmanager
#     environment:
#       - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

#   flink-taskmanager:
#     image: flink:1.17
#     depends_on:
#       - flink-jobmanager
#     command: taskmanager
#     environment:
#       - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

#   spark-master:
#     image: bitnami/spark:latest
#     environment:
#       - SPARK_MODE=master
#     ports:
#       - "7077:7077"     # Spark master port
#       - "8083:8080"     # Spark web UI

#   spark-worker:
#     image: bitnami/spark:latest
#     environment:
#       - SPARK_MODE=worker
#       - SPARK_MASTER_URL=spark://spark-master:7077
#     depends_on:
#       - spark-master
#     ports:
#       - "8084:8080"

# volumes:
#   mongo_data:
