services:

  # ----------------------------
  # Spark Master
  # ----------------------------
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "7077:7077"   # Spark master port
      - "8080:8080"   # Spark master web UI
    networks:
      - retail-net

  # ----------------------------
  # Spark Worker
  # ----------------------------
  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # Spark worker web UI
    networks:
      - retail-net

  # ----------------------------
  # Spark Submit Node
  # ----------------------------
  spark-submit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-submit
    entrypoint: /bin/bash
    command: -c "useradd -m -u 1000 spark && export HOME=/tmp && export USER=spark && sleep infinity"
    user: root
    environment:
      - HOME=/tmp
      - USER=spark
      - SPARK_SUBMIT_OPTS=-Divy.cache.dir=/tmp/.ivy2 -Divy.home=/tmp/.ivy2
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./jars:/opt/spark-extra-jars
      - ./conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf

    depends_on:
      - spark-master
      - spark-worker
    networks:
      - retail-net

  # ----------------------------
  # Kafka (Bitnami)
  # ----------------------------
  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=MDEyMzQ1Njc4OWFiY2RlZg==
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami
    networks:
      - retail-net

  # ----------------------------
  # MinIO
  # ----------------------------
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    networks:
      - retail-net

networks:
  retail-net:

volumes:
  minio-data:
  kafka-data: